#!/bin/bash
# ===================================================================================================== #
## Name: OpenVPN
## Description: This init script creates an OpenVPN Server and Client configuration files froma a base
## 				install of Debian 8.5
# Linux Server Build: OpenVPN From Scratch - Hak5 2019  - https://www.youtube.com/watch?v=XcsQdtsCS1U
# ===================================================================================================== #
#
# Dependencies
apt-get install easy-rsa openvpn ufw -y


#Enable IP forwarding
echo "1" > /proc/sys/net/ipv4/ip_forward

# Building your keys
cp -R /usr/share/easy-rsa /etc/openvpn; cd /etc/openvpn/easy-rsa
. ./vars  # set environment variables
./clean-all

# Generate Server cert
./build-ca

# Generate Diffie-Hellman Params
## Make that encryption your bitch
./build-dh

nano /etc/sysctl.conf
#uncomment net.ipv4.ip_forward=1
#save and exit

# Setup Firewall
ufw status
ufw allow ssh
ufw allow 1194/udp

#Let packets forward through the VPS by changing for forward policy to accept

nano /etc/default/ufw
#replace DROP with ACCEPT in DEFAULT_FORWARD_POLICY="DROP"
#save and exit



